export enum Action {
	ADD_NEW_OPTION = "ADD_NEW_OPTION",
	ADD_CLAUSE = "ADD_CLAUSE",
	DELETE_CLAUSE = "DELETE_CLAUSE",
	CLEAR_SQL = "CLEAR_SQL",
	ADD_FILTER = "ADD_FILTER",
	ADD_TABLE = "ADD_TABLE",
	ADD_TAG = "ADD_TAG",
	DELETE_TAG = "DELETE_TAG",
	SET_TABLE = "SET_TABLE",
	ADD_COLUMN = "ADD_COLUMN",
}

export enum TagType {
	CLAUSE = "CLAUSE",
	KEYWORD = "KEYWORD",
	TABLENAME = "TABLENAME",
	COLUMN = "COLUMN",
}
